FROM roquie/composer-parallel

COPY . /app
RUN composer install --no-ansi --no-interaction --no-progress --no-scripts --optimize-autoloader --ignore-platform-reqs

FROM roquie/docker-swoole-webapp:php7.3-latest-brotli

COPY --from=0 /app /app

RUN apk --no-cache update \
    && apk --no-cache add g++ make autoconf automake libtool bison re2c \
    && yes | pecl install xdebug \
    && echo -e "zend_extension=/usr/local/lib/php/extensions/no-debug-non-zts-20180731/xdebug.so\nxdebug.coverage_enable=1" > /usr/local/etc/php/php.ini

RUN vendor/bin/phpunit --coverage-clover=/app/coverage.xml

ENTRYPOINT cp /app/coverage.xml /tmp
