FROM roquie/composer-parallel

COPY . /app
RUN composer install --no-ansi --no-interaction --no-progress --no-scripts --optimize-autoloader --ignore-platform-reqs

FROM roquie/docker-swoole-webapp:7.3-latest

COPY --from=0 /app /app

EXPOSE 8080
WORKDIR /app

ENTRYPOINT vendor/bin/phpunit
CMD ["sh", "-c", "vendor/bin/phpunit"]
