version: 2
jobs:
  test_deps:
    docker:
      # specify the version you desire here
      - image: roquie/composer-parallel

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: composer install -n --prefer-dist --ignore-platform-reqs

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}
  test_run:
    docker:
      # specify the version you desire here
      - image: spacetabio/amphp-alpine:7.4-wkhtmltopdf-xdebug-1.1.0

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-

      - run: vendor/bin/phpstan analyse src --level 6
      - run: vendor/bin/phpunit --coverage-clover=coverage.xml
      - run: apk add bash
      - run: bash -c "bash <(curl -s https://codecov.io/bash)"

  deploy_latest:
    machine: true
    steps:
      - checkout
      - run:
          name: Create docker image for static server
          command: docker build -t microparts/static-server-php:latest .
      - run:
          name: Login to Docker Hub and push image
          command: |
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push microparts/static-server-php:latest

workflows:
  version: 2
  test_app:
    jobs:
      - test_deps
      - test_run:
          requires:
            - test_deps
  deploy_latest:
    jobs:
      - deploy_latest:
          filters:
            branches:
              only:
                - master
