version: 2
jobs:
  build:
    machine: true
    steps:
      - run:
          name: Build image
          command: make image IMAGE=unit FILE=Dockerfile.test
      - run:
          name: Run tests
          command: make run IMAGE=unit

