version: 2
jobs:
  build:
    machine: true
    steps:
      - run:
          name: Build image
          command: docker build -f Dockerfile.test -t unit:latest .
      - run:
          name: Run tests
          command: docker run --rm -it unit:latest

