version: 2
jobs:
  test:
    machine: true
    steps:
      - checkout
      - run:
          name: Create testing environment & Run tests
          command: docker build -f Dockerfile.test -t unit:latest .
      - run:
          name: Send code coverage report to Codecov
          command: |
            docker run --rm -it -v $(pwd)/coverage:/tmp unit:latest
            bash <(curl -s https://codecov.io/bash)

  deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: Create docker image for static server
          command: docker build -t microparts/static-server-php:latest .
      - run:
          name: Login to Docker Hub and push image
          command: |
            export TAG=$(git describe --tags $(git rev-list --tags --max-count=1))

            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push microparts/static-server-php:latest
            docker tag microparts/static-server-php:latest microparts/static-server-php:$TAG
            docker push microparts/static-server-php:$TAG

workflows:
  version: 2
  test:
    jobs:
      - test
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
  cron:
    triggers:
      - schedule:
          cron: "0 0 * * 1" # Every week on Monday
          filters:
            branches:
              only:
                - master
    jobs:
      - deploy
